### ISSUE TITLE
Crash Tracker einbauen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#1]
Evtl auch mit den Google Dev. Tools. Da kann man sich die Abstürze auch anzeigen lassen habe ich gesehen.

**Comment by IHFSchwarz** [comment]
Habe grade mal recherchiert. Es scheint so als sei das error reporting bei google play standardmäßig aktiv, sofern die app über darüber installiert wurde.
Referenz: https://support.google.com/googleplay/android-developer/answer/6083203
Und: https://www.toptal.com/android/automated-android-crash-reports-with-acra-and-cloudant
Komplett automatisiert würde ich die crash reports nicht senden lassen, aber evtl, wenn die Google Play Dev Console nicht reicht, über ACRA.
Dort könnte man reports über E-Mail oder automatisiertes error reporting anbieten. Bei letzterem würde ich den user aber beim ersten Start um seine Einverständnis bitten.

**Comment by dh3wr** [comment]
Wenn google die Error Reports anfängt und entgegennimmt, dann ist ja alles gut.

**Comment by IHFSchwarz** [comment]
OK, für's erste schließe ich die Issue.
