### ISSUE TITLE
App für Blinde begreifbar machen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#19]
Email erhalten:

Hallo ich bin ein Blinder Funkamateur
dh0yay

Ich arbeite mit dem Screenreader talkback von Google der für blinde und sehbehinderte gemacht wurde um ein Smartphone zu bedienen, es wäre schön wenn j das Programm so anpassen könnte das alle Schaltflächen beschriftet sind, Schalter Schaltflächen Daypacks und so weiter

**Comment by IHFSchwarz** [comment]
Der FloatingActionButton und das Messagefeld bei der Post call activity scheinen keinen entsprechenden text für TalkBalk zu haben.

**Comment by IHFSchwarz** [comment]
Das Messagefeld wird seit 99fb988db9ec16fff5849fa5fa4d1799c7a0c672 vorgelesen. Beim FloatingActionButton muss ich noch eine Lösung suchen, da es weder text noch name noch hint als XML Attribut hat. Eventuell lässt sich das Problem mit labelFor beheben, bisher schien das aber nicht so.

**Comment by IHFSchwarz** [comment]
Der FAB wird seit  5a105b4 auch vorgelesen sowie das User Feld beim login.

**Comment by IHFSchwarz** [comment]
Noch weiß ich nicht ob ich diese Issue aufhalten werde. Es wäre gut, weiteres feedback von einem aktiven Nutzer einzuholen, ob etwas nicht vorgelesen wird. Wir können diese Issue auch im weiteren Verlauf zum tracking dieser bugs benutzen.

**Comment by IHFSchwarz** [comment]
Momentan scheint alles vorlesbar. Wenn weiterhin Probleme bestehen, würde ich gerne eine entsprechende E-Mail oder eine Issue bekommen bezogen auf das fehlende Element.
