### ISSUE TITLE
Core Version ebenfalls in App anzeigen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#20]
Vielleicht App V 1.0.3, Core 1.3.3.2 . Vielleicht auch 2 zeilig?

Die Version kann vom Core geholt werden. Wie weiß @MarvinMenzerath

**Comment by IHFSchwarz** [comment]
Wird implementiert wenn https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/93  erledigt ist.
