### ISSUE TITLE
Automatische APRS-Standortmeldung des Senders abschaltbar machen

### ISSUE THREAD

**Issue by MurrayBozinsky** [DecentralizedAmateurPagingNetwork/DAPNETApp#22]
Hallo,
aktuell werden die Standorte der POCSAG-Sender von PE2KMV
ins APRS-Netz unter der Kennung "PS-<Rufzeichen des Senders>"
eingespeist. 
Wäre es möglich diese Funktion für jeden Sender konfigurierbar zu machen ?
Sinnvoll wären die Optionen "Aus" und  "Einspeisen nur wenn online",
zusätzlich wäre eine konfigurierbare Sendehäufigkeit sinnvoll.

Hintergrund: Wenn man am selben Standort des POCSAG-Senders eine
für APRS sinnvollere Applikation wie eine Wetterstation betreibt, will man
nicht, dass deren Icon andauernd durch die "<call>-PS" zugedeckt wird.
Weiterhin halte ich es nicht für sinnvoll, _generell_ die Standorte von
ausser Betrieb befindlichen Sendern oder von 10mW-RasPagern ins APRS-IS
zu senden - sowas sollte besser vom Stationsbetreiber konfigurierbar sein.

**Comment by dh3wr** [comment]
Was hat das mit der App zu tun? Ich glaube du bist im falschen repo.
