### ISSUE TITLE
Nicht-Admins Rufe bringen die APP zum abstürzen

### ISSUE THREAD

**Issue by DK6FC** [DecentralizedAmateurPagingNetwork/DAPNETApp#23]
Hallo, 

mit dem letzten Patch funktionierte Menü - Calls wieder nicht. Beim drauf klicken stürzt die APP ab. 

Gruß
Johannes DK6FC

**Comment by IHFSchwarz** [comment]
Danke für den bug report! Werde mir dem Problem so schnell wie möglich annehmen, konnte es aber bisher noch nicht reproduzieren.

**Comment by IHFSchwarz** [comment]
Das Problem sollte behoben sein. Wenn weitere Probleme bestehen, bitte sowohl den Absturzbericht abschicken als auch hier anmerken.

**Comment by DK6FC** [comment]
Problem besteht weiterhin. Wie kann ich euch das log zukommen lassen bzw. 
Wo find ich das Crashlog auf meinem Mobile?

Gruß
Johannes




Am 17. Mai 2017 14:14:47 schrieb IHFSchwarz <notifications@github.com>:

**Comment by DK6FC** [comment]
Problem behoben mit dem aktuellem Relaese, danke!
