### ISSUE TITLE
Alternative Stores

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#25]
Es kam gerade rein
![grafik](https://cloud.githubusercontent.com/assets/16710361/26155779/a5966404-3b14-11e7-97f2-16c0a119cdcd.png)

Bis jetzt kannte ich das noch nicht mal. Wenn wir Lust haben, können wir uns dem ja mal annehmen.

**Comment by IHFSchwarz** [comment]
Ehrlich gesagt habe ich f-droid von Anfang eingeplant.
Deswegen würde ich auch osmdroid und nicht die proprietäre Maps API verwenden. Freut mich, dass auch andere das gut fänden! Uptodown kannte ich auch nicht, aber aptoide und amazon wären noch eine idee, f-droid würde ich aber höher priorisieren.

Habe auch schon die Liste mit Bedingungen von f-Droid gecheckt. Wir erfüllen soweit ich das sehe alles, ich bin mir nur nicht sicher bezüglich der Lizenzen unserer logos. Kannst du das aufklären?
[Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy)
[Inclusion How-To](https://f-droid.org/wiki/page/Inclusion_How-To)

**Comment by dh3wr** [comment]
CC NC-BY-SA

**Comment by IHFSchwarz** [comment]
Issue requesting inclusion has been created: https://gitlab.com/fdroid/rfp/issues/152

**Comment by IHFSchwarz** [comment]
Die App befindet sich nun bei F-Droid im Store.
Als weitere Kandidaten stünden diese zur Auswahl:

Aptoide (open-source):
~100M Users
https://www.aptoide.com/developers

Amazon Appstore:
Fire OS Users
99$ (first year free, 50$ AWS voucher)
https://developer.amazon.com/app-submission

Uptodown:
~60M Users
https://en.uptodown.com/developers/zone

Persönlich halte ich Aptoide für sinnvoll, da die Inklusion kostenlos ist und es OSS ist. Der Amazon Appstore ist für die Familie der Fire Geräte sinnvoll, jedoch fallen immer noch die Gebühren an und wir besitzen kein testgerät.

Für's erste schließe ich damit die Issue, wenn jemand seine Unterstützung für einen Store bekunden will, kann die Person das gerne hier tun.
