### ISSUE TITLE
OK Google/WearOS Support

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#29]
Spielerei:
Android Wear unterstützen. Quasi:
``"OK Google, sende Funkruf an D H 3 W R mit Inhalt Das ist aber ein tooles Feature"``

Wie bei SMS oder IM Nachrichten

Ein paar Infos:

- https://jaxenter.de/android-am-arm-2-28150
- https://www.android-user.de/workshop-einstieg-in-die-android-programmierung-mit-android-wear-teil-1

**Comment by IHFSchwarz** [comment]
Google unterstützt offiziell diese Voice commands: https://developers.google.com/voice-actions/system/
Bereits seit [2015](https://search.googleblog.com/2015/07/rest-your-thumbs-ask-google-to-send.html) gibt es inoffiziellen Zugriff auf den messaging command, jedoch nirgendwo dokumentiert und dadurch nur für ausgewählte Apps. Bis Google sich dazu entscheidet das Ganze zu öffnen wird das hier wohl nichts...
