### ISSUE TITLE
Kartenansicht der Sender einbauen

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#3]
Wie auf http://hampager.de/#/transmitters/map  Es gibt eine Leaflet-Variante glaub ich für Android. Sonst Google Maps.

**Comment by IHFSchwarz** [comment]
Eine gute alternative wäre auch https://github.com/osmdroid/osmdroid. Vielleicht kann man da sogar tiles aus dem Hamnet fetchen.

**Comment by dh3wr** [comment]
- [ ] Die Anzeige der Transmission Power im Popup braucht keinen Zeilenumbruch.
- [ ] Bei den Ownern muss kein [ ] um die Inhalte herum sein.
- [ ] Ändere ``Timeslot`` in ``Timeslots``, wenn es mehr als einen gibt.
- [ ] Aufnahme der Popup-Texte in die Strings-Übersicht, damit man die auch übersetzen kann.
- [ ] Ändere ``Usage`` in ``Type``

**Comment by IHFSchwarz** [comment]
Der Zeilenumbruch erschließt sich für mich noch nicht - Vielleicht ist das auch ein library Problem.
