### ISSUE TITLE
Nicht-Admins Rufe zurück Button führt zu Logout

### ISSUE THREAD

**Issue by DK6FC** [DecentralizedAmateurPagingNetwork/DAPNETApp#35]
Moin Moin,

Wenn man die App öffnet sich einloggt und über das Menü Calls anwählt und dann die zurück Taste am Android Gerät benutzt ist man wieder ausgeloggt. Macht man den gleichen Schritte nicht übers Menü sondern den Brief Button bleibt man eingeloggt.

**Comment by IHFSchwarz** [comment]
Danke für die Issue!

Mir ist dieses Problem auch schon aufgefallen. In Wahrheit ist man jedoch nicht ausgeloggt, die Mainactivity, in der das Menü eingebettet und von der andere Activities gestartet werden, erkennt nicht, dass man eingeloggt ist.

Ein ähnliches Problem dürfte auftreten, wenn man eingeloggt ist, sich ausloggt und direkt wieder den zurück Button drückt.
Die App/Mainactivity erkennt dann erst den status beim nächsten neustart.
Es sollte möglich sein, auf den back button das menü in der mainactivity zu clearen und neu aufzubauen sowie zurückzukehren. Ich schau es mir mal an.

**Comment by IHFSchwarz** [comment]
Das Problem mit den calls sollte temporär gefixt sein.
