### ISSUE TITLE
Cache callsigns and transmittergroups

### ISSUE THREAD

**Issue by IHFSchwarz** [DecentralizedAmateurPagingNetwork/DAPNETApp#42]
Useful if your network connection is unstable. Refreshing should be done automatically after 24 hours (adjustable?) and manually.

**Comment by dh3wr** [comment]
You should always refresh the cache and use the cached values if network connection is not successful after 3 seconds.

**Comment by dh3wr** [comment]
Same for transmitters later.

**Comment by IHFSchwarz** [comment]
Caching will now always used cached values. If the connection fetching callsigns and transmittergroups succeeds, they auto-overwrite cached and displayed Objects.
