### ISSUE TITLE
Bei Calls gibt es 400 Fehler wenn man nicht einen Eintrag aus der Liste auswählt

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#45]
Wenn man auf senden drückt, bevor ein Eintrag aus der Liste ausgewählt ist, kommt 400.

**Comment by IHFSchwarz** [comment]
Bei non-existenten Callsigns wird weiterhin ein Fehler 400 angezeigt, bekannte Callsigns werden jecoch übernommen. Dies sollte erwartetes Verhalten sein, oder?
