### ISSUE TITLE
Neue URL für Munin-Statistik

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#55]
Bitte dies als neue URL benutzen. Falls zwischen Internet und HAMNET unterschieden wird:
https://www.afu.rwth-aachen.de/munin-cgi/munin-cgi-graph/db0sda.ampr.org/dapnet.db0sda.ampr.org/dapnet-week.png

http://db0sda.ampr.org/munin-cgi/munin-cgi-graph/db0sda.ampr.org/dapnet.db0sda.ampr.org/dapnet-week.png

Sonst nur die www.-URL

**Comment by dh3wr** [comment]
Ist das schon auf google-Play? Meine App zeigt immer noch das alte Bild an.

**Comment by IHFSchwarz** [comment]
Ich sehe jetzt in der App aus dem store das aktuelle Bild, der commit war noch nicht im release.
