### ISSUE TITLE
Switching from hampager.de to dapnet.db0sda.ampr.org

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#58]
Kann es sein, dass automatisch von der Internet- auf die HAMNET-Adresse gewechselt wird, dann aber nicht wieder zurück? Ich hatte schon öfter, dass der Zugriff nicht mehr ging und wenn ich mich dann ab- und angemeldet habe, war der HAMNET-Eintrag ausgewählt.

**Comment by IHFSchwarz** [comment]
Der switch wird in der App jetzt nur beim login durchgeführt. Für den tiefergehenden, automatischen switch werde ich ein issue im DAP4J repo aufmachen.
