### ISSUE TITLE
Betrifft: URL-Unterscheidung HAMNET/Internet

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#61]
Hier nochmal die Übersicht für die URLs von Munin-Grafik und Kachel-Server

Unterscheidung:
HAMNET: Wenn API Server URL innerhalb von 44.0.0.0/8, oder Domain-Name enthält ``.ampr.org``
Internet: Sonst

URL Karten-Server:
Internet: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
HAMNET: http://karten.db0sda.ampr.org/osm/{z}/{x}/{y}.png  (kein Loadbalancing so einfach möglich)

Munin-URL: Siehe #55 

Abdeckungskarten (#54):
Internet (Beispiel für db0sea): https://hampager.de/assets/coverage/on0sea.png
HAMNET (Beispiel für db0sea): http://dapnet.db0sda.ampr.org/assets/coverage/on0sea.png

**Comment by IHFSchwarz** [comment]
Die relevanten URLs (Karten, Abdeckungskarten) habe ich mal in eigene Issues ausgelagert.
Bzgl "cron-job" o.ä. habe ich ja schon in #58 geschrieben. Auch diese Issue wird in DAP4J einfließen.
