### ISSUE TITLE
Sound announce when new msg arrive 

### ISSUE THREAD

**Issue by sp2ong** [DecentralizedAmateurPagingNetwork/DAPNETApp#66]
Hi,

It will be nice add sound announce when a new message arrives at our folder "Calls".

73 Waldek SP2ONG

**Comment by dh3wr** [comment]
Dear Waldek,

There will be no transmission of calls directed to you on the app, as we are not implementing an app based instant messenger. So there will be also no sound :-)

The only device to make sound upon arrival of messages for you should be your POCSAG-RX.
