### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [DecentralizedAmateurPagingNetwork/DAPNETApp#72]
Dear developer! 
In the process of using, I found a bug in layout / display. As shown in the figure, in the DANET page, text overlap with each other.
App version is 1.1.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size_** are the largest ! ! ! Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![bug-dapnetmoblie_23](https://user-images.githubusercontent.com/18572115/103082622-7c623300-4615-11eb-8aaa-169b86f0a265.png)

**Comment by dh3wr** [comment]
Hello @franklinbill 
thanks for pointing out this bug. There is currently no active maintainance of this app, but in case this will change some time in the future, we'll keep this in mind.
Best regards

**Comment by dh3wr** [comment]
Hello @franklinbill 
There has been an update. Please check again with your setup/setting.

**Comment by franklinbill** [comment]
It's ok！Thank you very much！

**Comment by dh3wr** [comment]
Thanks to @kking
