### ISSUE TITLE
Genau 80 Zeichen liefern trotzdem Fehler

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/DAPNETApp#8]
Wenn man genau 80 / 80 Zeichen eingibt, sagt die APP Message above 80 Characters.

Text ändern in
Message longer than maximum of 80 characters.

**Comment by IHFSchwarz** [comment]
Sollte durch 672d70dfc49667941991520cbf7ee90d1cddce14 gefixt sein.
